kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dashgram-job-volumeclaim
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi